version: "3"
services:
  app:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    ports:
      - 7007:7007
    volumes:
      - ./credentials:/app/credentials
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: password

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: password
